// CHATS
export const CHATS_LOADING = 'CHATS_LOADING'
export const CHATS_COMPLETED = 'CHATS_COMPLETED'

// CHAT
export const CHAT_LOADING = 'CHAT_LOADING'
export const CHAT_COMPLETED = 'CHAT_COMPLETED'

// SOCKET
export const SOCKET_LOADING = 'SOCKET_LOADING'
export const SOCKET_COMPLETED = 'SOCKET_COMPLETED'